CREATE TABLE [dbo].[usa_jails]
(
[facility_id] [float] NULL,
[facility_name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[zip] [float] NULL,
[inmate_confined] [float] NULL,
[inmate_population_daily] [float] NULL,
[facility_count] [float] NULL,
[facility_new] [float] NULL,
[facility_new_notes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[facility_close] [float] NULL,
[facility_close_notes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[facility_static] [float] NULL,
[jail_payroll_ft] [float] NULL,
[jail_payroll_pt] [float] NULL,
[jail_staff_assault] [float] NULL,
[jail_staff_assault_count] [float] NULL,
[jail_work_release] [float] NULL,
[jail_work_release_count] [float] NULL,
[jail_education_count] [float] NULL,
[jail_authority_72h] [float] NULL,
[jail_sentencing_1y_under] [float] NULL,
[jail_sentencing_1y_over] [float] NULL,
[jail_temp] [float] NULL,
[jail_gender] [float] NULL,
[jail_capacity_rated] [float] NULL,
[inmate_adult_male] [float] NULL,
[inmate_adult_female] [float] NULL,
[inmate_juvenile_male] [float] NULL,
[inmate_juvenile_female] [float] NULL,
[inmate_population] [float] NULL,
[construction_year] [float] NULL,
[construction_renovation] [float] NULL,
[construction_renovation_year] [float] NULL
) ON [PRIMARY]
GO
