CREATE TABLE [dbo].[zcta_cousub_rel_10]
(
[ZCTA5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUSUB] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLASSFP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GEOID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POPPT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HUPT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AREAPT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AREALANDPT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZPOP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZHU] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZAREA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZAREALAND] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSPOP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSHU] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSAREA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSAREALAND] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZPOPPCT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZHUPCT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZAREAPCT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZAREALANDPCT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSPOPPCT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSHUPCT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSAREAPCT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSAREALANDPCT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
