CREATE TABLE [dbo].[macro_geo_info_states_2008]
(
[state] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state_abbr] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[census_region] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[census_geo_division] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[population] [float] NULL,
[le_employees] [float] NULL,
[le_officers_male] [float] NULL,
[le_officers_female] [float] NULL,
[le_civilians_male] [float] NULL,
[le_civilians_female] [float] NULL,
[agency_count] [float] NULL,
[crime_murder] [float] NULL,
[crime_murder_firearms] [float] NULL,
[crime_murder_handguns] [float] NULL,
[crime_murder_rifles] [float] NULL,
[crime_murder_shotguns] [float] NULL,
[crime_murder_firearm_unk] [float] NULL,
[crime_murder_knives] [float] NULL,
[crime_murder_other] [float] NULL,
[crime_murder_hands] [float] NULL,
[crime_robbery] [float] NULL,
[crime_robbery_firearms] [float] NULL,
[crime_robbery_knives] [float] NULL,
[crime_robbery_other] [float] NULL,
[crime_robbery_strongarm] [float] NULL,
[crime_violent] [float] NULL,
[crime_violent_100k] [float] NULL,
[crime_murder2] [float] NULL,
[crime_murder2_100k] [float] NULL,
[crime_rape] [float] NULL,
[crime_rape_100k] [float] NULL,
[crime_robbery2] [float] NULL,
[crime_robbery2_100k] [float] NULL,
[crime_assault] [float] NULL,
[crime_assault_100k] [float] NULL,
[crime_property] [float] NULL,
[crime_property_100k] [float] NULL,
[crime_burglary] [float] NULL,
[crime_burglary_100k] [float] NULL,
[crime_larceny] [float] NULL,
[crime_larceny_100k] [float] NULL,
[crime_vehicle] [float] NULL,
[crime_vehicle_100k] [float] NULL
) ON [PRIMARY]
GO
