CREATE TABLE [dbo].[StateOffenses]
(
[StateFips] [tinyint] NULL,
[StateName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Population] [int] NULL,
[Population100k] [real] NULL,
[ViolentCrime] [int] NULL,
[ViolentCrimePer100k] [real] NULL,
[ViolentCrimePer100kNatlAvg] [real] NULL,
[ViolentCrimeRelNatlAvg] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ViolentCrimePer100kMinState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ViolentCrimePer100kMaxState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ViolentCrimePer100kMinStateValue] [real] NULL,
[ViolentCrimePer100kMaxStateValue] [real] NULL,
[MurderAndNonNegligentManslaughter] [int] NULL,
[MurderAndNonNegligentManslaughterPer100k] [real] NULL,
[MurderAndNonNegligentManslaughterPer100kNatlAvg] [real] NULL,
[MurderAndNonNegligentManslaughterRelNatlAvg] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MurderAndNonNegligentManslaughterPer100kMinState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MurderAndNonNegligentManslaughterPer100kMaxState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MurderAndNonNegligentManslaughterPer100kMinStateValue] [real] NULL,
[MurderAndNonNegligentManslaughterPer100kMaxStateValue] [real] NULL,
[ForcibleRape] [int] NULL,
[ForcibleRapePer100k] [real] NULL,
[ForcibleRapePer100kNatlAvg] [real] NULL,
[ForcibleRapeRelNatlAvg] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ForcibleRapePer100kMinState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ForcibleRapePer100kMaxState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ForcibleRapePer100kMinStateValue] [real] NULL,
[ForcibleRapePer100kMaxStateValue] [real] NULL,
[Robbery] [int] NULL,
[RobberyPer100k] [real] NULL,
[RobberyPer100kNatlAvg] [real] NULL,
[RobberyRelNatlAvg] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RobberyPer100kMinState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RobberyPer100kMaxState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RobberyPer100kMinStateValue] [real] NULL,
[RobberyPer100kMaxStateValue] [real] NULL,
[AggravatedAssault] [int] NULL,
[AggravatedAssaultPer100k] [real] NULL,
[AggravatedAssaultPer100kNatlAvg] [real] NULL,
[AggravatedAssaultRelNatlAvg] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AggravatedAssaultPer100kMinState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AggravatedAssaultPer100kMaxState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AggravatedAssaultPer100kMinStateValue] [real] NULL,
[AggravatedAssaultPer100kMaxStateValue] [real] NULL,
[PropertyCrime] [int] NULL,
[PropertyCrimePer100k] [real] NULL,
[PropertyCrimePer100kNatlAvg] [real] NULL,
[PropertyCrimeRelNatlAvg] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyCrimePer100kMinState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyCrimePer100kMaxState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyCrimePer100kMinStateValue] [real] NULL,
[PropertyCrimePer100kMaxStateValue] [real] NULL,
[Burglary] [int] NULL,
[BurglaryPer100k] [real] NULL,
[BurglaryPer100kNatlAvg] [real] NULL,
[BurglaryRelNatlAvg] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BurglaryPer100kMinState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BurglaryPer100kMaxState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BurglaryPer100kMinStateValue] [real] NULL,
[BurglaryPer100kMaxStateValue] [real] NULL,
[LarcenyTheft] [int] NULL,
[LarcenyTheftPer100k] [real] NULL,
[LarcenyTheftPer100kNatlAvg] [real] NULL,
[LarcenyTheftRelNatlAvg] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LarcenyTheftPer100kMinState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LarcenyTheftPer100kMaxState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LarcenyTheftPer100kMinStateValue] [real] NULL,
[LarcenyTheftPer100kMaxStateValue] [real] NULL,
[MotorVehicleTheft] [int] NULL,
[MotorVehicleTheftPer100k] [real] NULL,
[MotorVehicleTheftPer100kNatlAvg] [real] NULL,
[MotorVehicleTheftRelNatlAvg] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MotorVehicleTheftPer100kMinState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MotorVehicleTheftPer100kMaxState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MotorVehicleTheftPer100kMinStateValue] [real] NULL,
[MotorVehicleTheftPer100kMaxStateValue] [real] NULL,
[Arson] [int] NULL,
[ArsonPer100k] [real] NULL,
[ArsonPer100kNatlAvg] [real] NULL,
[ArsonRelNatlAvg] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArsonPer100kMinState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArsonPer100kMaxState] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ArsonPer100kMinStateValue] [real] NULL,
[ArsonPer100kMaxStateValue] [real] NULL,
[Year] [int] NULL,
[PopulationRankState] [int] NULL,
[LandAreaState] [int] NULL,
[LandAreaRankState] [int] NULL
) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [IX_StateOffenses] ON [dbo].[StateOffenses] ([StateFips]) ON [PRIMARY]
GO
