SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROC spCacheGet(@Key VARCHAR(MAX)) AS
	SET NOCOUNT ON
	DECLARE @HashKey BINARY(20)=HASHBYTES('sha1',@Key)
	SELECT * FROM Cache WHERE HashKey=@HashKey
GO
