SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dbo].[fnNiceTime](@D DATETIME) RETURNS VARCHAR(8) AS
BEGIN
	DECLARE 
		@H INT=DATEPART(hour,@D),
		@M INT=DATEPART(minute,@D)

	RETURN 
		CONVERT(VARCHAR,CASE WHEN @H > 12 THEN @H-12 ELSE @H END)+':'+
		CASE WHEN @M<10 THEN '0' ELSE '' END + CONVERT(VARCHAR,@M)+' '+
		CASE WHEN @H>=12 THEN 'P' ELSE 'A' END + 'M'
END
GO
