//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aci.X.IwsLib.Commerce.v2_1.Catalog {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", ConfigurationName="Commerce.v2_1.Catalog.CatalogServicesPortType")]
    public interface CatalogServicesPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/catalog.php/GetAddons", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aci.X.IwsLib.Commerce.v2_1.Catalog.GetAddonsResponse GetAddons(Aci.X.IwsLib.Commerce.v2_1.Catalog.GetAddonsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/catalog.php/GetAddons", ReplyAction="*")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Catalog.GetAddonsResponse> GetAddonsAsync(Aci.X.IwsLib.Commerce.v2_1.Catalog.GetAddonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/catalog.php/GetProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aci.X.IwsLib.Commerce.v2_1.Catalog.GetProductResponse GetProduct(Aci.X.IwsLib.Commerce.v2_1.Catalog.GetProductRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/catalog.php/GetProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Catalog.GetProductResponse> GetProductAsync(Aci.X.IwsLib.Commerce.v2_1.Catalog.GetProductRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class ClientAuthType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIDField;
        
        private string authIDField;
        
        private string authKeyField;
        
        /// <remarks/>
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
                this.RaisePropertyChanged("ClientID");
            }
        }
        
        /// <remarks/>
        public string AuthID {
            get {
                return this.authIDField;
            }
            set {
                this.authIDField = value;
                this.RaisePropertyChanged("AuthID");
            }
        }
        
        /// <remarks/>
        public string AuthKey {
            get {
                return this.authKeyField;
            }
            set {
                this.authKeyField = value;
                this.RaisePropertyChanged("AuthKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class ProductItemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int productIDField;
        
        private bool productIDFieldSpecified;
        
        private string productTokenField;
        
        /// <remarks/>
        public int ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
                this.RaisePropertyChanged("ProductID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductIDSpecified {
            get {
                return this.productIDFieldSpecified;
            }
            set {
                this.productIDFieldSpecified = value;
                this.RaisePropertyChanged("ProductIDSpecified");
            }
        }
        
        /// <remarks/>
        public string ProductToken {
            get {
                return this.productTokenField;
            }
            set {
                this.productTokenField = value;
                this.RaisePropertyChanged("ProductToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class Module : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int moduleIDField;
        
        private string titleField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int ModuleID {
            get {
                return this.moduleIDField;
            }
            set {
                this.moduleIDField = value;
                this.RaisePropertyChanged("ModuleID");
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class SplitPackage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private string descriptonField;
        
        private decimal savingsField;
        
        private bool savingsFieldSpecified;
        
        private string productReferenceIDField;
        
        private string productIDField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        public string Descripton {
            get {
                return this.descriptonField;
            }
            set {
                this.descriptonField = value;
                this.RaisePropertyChanged("Descripton");
            }
        }
        
        /// <remarks/>
        public decimal Savings {
            get {
                return this.savingsField;
            }
            set {
                this.savingsField = value;
                this.RaisePropertyChanged("Savings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SavingsSpecified {
            get {
                return this.savingsFieldSpecified;
            }
            set {
                this.savingsFieldSpecified = value;
                this.RaisePropertyChanged("SavingsSpecified");
            }
        }
        
        /// <remarks/>
        public string ProductReferenceID {
            get {
                return this.productReferenceIDField;
            }
            set {
                this.productReferenceIDField = value;
                this.RaisePropertyChanged("ProductReferenceID");
            }
        }
        
        /// <remarks/>
        public string ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
                this.RaisePropertyChanged("ProductID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class DelayedBill : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Duration durationField;
        
        /// <remarks/>
        public Duration Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class Duration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EnumerationOfUnit unitField;
        
        private int amountField;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        /// <remarks/>
        public EnumerationOfUnit Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("PriceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public enum EnumerationOfUnit {
        
        /// <remarks/>
        HOUR,
        
        /// <remarks/>
        DAY,
        
        /// <remarks/>
        MONTH,
        
        /// <remarks/>
        YEAR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class SubscriptionDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private string descriptonField;
        
        private decimal savingsField;
        
        private bool savingsFieldSpecified;
        
        private string productReferenceIDField;
        
        private string productIDField;
        
        private int trialPeriodField;
        
        private bool trialPeriodFieldSpecified;
        
        private int recurrencePeriodField;
        
        private bool recurrencePeriodFieldSpecified;
        
        private Duration recurrenceDurationField;
        
        private decimal recurringPriceField;
        
        private string expirationField;
        
        private int featureSetIDField;
        
        private DelayedBill delayedBillField;
        
        private int serviceGroupIDField;
        
        private bool serviceGroupIDFieldSpecified;
        
        private int serviceIDField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        public string Descripton {
            get {
                return this.descriptonField;
            }
            set {
                this.descriptonField = value;
                this.RaisePropertyChanged("Descripton");
            }
        }
        
        /// <remarks/>
        public decimal Savings {
            get {
                return this.savingsField;
            }
            set {
                this.savingsField = value;
                this.RaisePropertyChanged("Savings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SavingsSpecified {
            get {
                return this.savingsFieldSpecified;
            }
            set {
                this.savingsFieldSpecified = value;
                this.RaisePropertyChanged("SavingsSpecified");
            }
        }
        
        /// <remarks/>
        public string ProductReferenceID {
            get {
                return this.productReferenceIDField;
            }
            set {
                this.productReferenceIDField = value;
                this.RaisePropertyChanged("ProductReferenceID");
            }
        }
        
        /// <remarks/>
        public string ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
                this.RaisePropertyChanged("ProductID");
            }
        }
        
        /// <remarks/>
        public int TrialPeriod {
            get {
                return this.trialPeriodField;
            }
            set {
                this.trialPeriodField = value;
                this.RaisePropertyChanged("TrialPeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrialPeriodSpecified {
            get {
                return this.trialPeriodFieldSpecified;
            }
            set {
                this.trialPeriodFieldSpecified = value;
                this.RaisePropertyChanged("TrialPeriodSpecified");
            }
        }
        
        /// <remarks/>
        public int RecurrencePeriod {
            get {
                return this.recurrencePeriodField;
            }
            set {
                this.recurrencePeriodField = value;
                this.RaisePropertyChanged("RecurrencePeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecurrencePeriodSpecified {
            get {
                return this.recurrencePeriodFieldSpecified;
            }
            set {
                this.recurrencePeriodFieldSpecified = value;
                this.RaisePropertyChanged("RecurrencePeriodSpecified");
            }
        }
        
        /// <remarks/>
        public Duration RecurrenceDuration {
            get {
                return this.recurrenceDurationField;
            }
            set {
                this.recurrenceDurationField = value;
                this.RaisePropertyChanged("RecurrenceDuration");
            }
        }
        
        /// <remarks/>
        public decimal RecurringPrice {
            get {
                return this.recurringPriceField;
            }
            set {
                this.recurringPriceField = value;
                this.RaisePropertyChanged("RecurringPrice");
            }
        }
        
        /// <remarks/>
        public string Expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
                this.RaisePropertyChanged("Expiration");
            }
        }
        
        /// <remarks/>
        public int FeatureSetID {
            get {
                return this.featureSetIDField;
            }
            set {
                this.featureSetIDField = value;
                this.RaisePropertyChanged("FeatureSetID");
            }
        }
        
        /// <remarks/>
        public DelayedBill DelayedBill {
            get {
                return this.delayedBillField;
            }
            set {
                this.delayedBillField = value;
                this.RaisePropertyChanged("DelayedBill");
            }
        }
        
        /// <remarks/>
        public int ServiceGroupID {
            get {
                return this.serviceGroupIDField;
            }
            set {
                this.serviceGroupIDField = value;
                this.RaisePropertyChanged("ServiceGroupID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServiceGroupIDSpecified {
            get {
                return this.serviceGroupIDFieldSpecified;
            }
            set {
                this.serviceGroupIDFieldSpecified = value;
                this.RaisePropertyChanged("ServiceGroupIDSpecified");
            }
        }
        
        /// <remarks/>
        public int ServiceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
                this.RaisePropertyChanged("ServiceID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class Discount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string discountTypeField;
        
        private decimal savingsAmountField;
        
        private string offerStatusField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string DiscountType {
            get {
                return this.discountTypeField;
            }
            set {
                this.discountTypeField = value;
                this.RaisePropertyChanged("DiscountType");
            }
        }
        
        /// <remarks/>
        public decimal SavingsAmount {
            get {
                return this.savingsAmountField;
            }
            set {
                this.savingsAmountField = value;
                this.RaisePropertyChanged("SavingsAmount");
            }
        }
        
        /// <remarks/>
        public string OfferStatus {
            get {
                return this.offerStatusField;
            }
            set {
                this.offerStatusField = value;
                this.RaisePropertyChanged("OfferStatus");
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class PriceDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productTokenField;
        
        private decimal mSRPPriceField;
        
        private bool mSRPPriceFieldSpecified;
        
        private decimal priceField;
        
        private decimal minimumPriceField;
        
        private bool minimumPriceFieldSpecified;
        
        private Discount[] discountsField;
        
        /// <remarks/>
        public string ProductToken {
            get {
                return this.productTokenField;
            }
            set {
                this.productTokenField = value;
                this.RaisePropertyChanged("ProductToken");
            }
        }
        
        /// <remarks/>
        public decimal MSRPPrice {
            get {
                return this.mSRPPriceField;
            }
            set {
                this.mSRPPriceField = value;
                this.RaisePropertyChanged("MSRPPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MSRPPriceSpecified {
            get {
                return this.mSRPPriceFieldSpecified;
            }
            set {
                this.mSRPPriceFieldSpecified = value;
                this.RaisePropertyChanged("MSRPPriceSpecified");
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        public decimal MinimumPrice {
            get {
                return this.minimumPriceField;
            }
            set {
                this.minimumPriceField = value;
                this.RaisePropertyChanged("MinimumPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinimumPriceSpecified {
            get {
                return this.minimumPriceFieldSpecified;
            }
            set {
                this.minimumPriceFieldSpecified = value;
                this.RaisePropertyChanged("MinimumPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Discount[] Discounts {
            get {
                return this.discountsField;
            }
            set {
                this.discountsField = value;
                this.RaisePropertyChanged("Discounts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class Product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productReferenceIDField;
        
        private string productIDField;
        
        private string productTypeField;
        
        private EnumerationOfAddonType addonTypeField;
        
        private bool addonTypeFieldSpecified;
        
        private string categoryTypeField;
        
        private string groupNameField;
        
        private string titleField;
        
        private string descriptionField;
        
        private int unitsField;
        
        private int quantityField;
        
        private PriceDetails[] priceListingsField;
        
        private SubscriptionDetails subscriptionDetailsField;
        
        private SplitPackage splitPackageDetailsField;
        
        private SplitPackage subscriptionSplitPackageDetailsField;
        
        private Module[] fulfillmentModulesField;
        
        private int fulfillmentBundleField;
        
        /// <remarks/>
        public string ProductReferenceID {
            get {
                return this.productReferenceIDField;
            }
            set {
                this.productReferenceIDField = value;
                this.RaisePropertyChanged("ProductReferenceID");
            }
        }
        
        /// <remarks/>
        public string ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
                this.RaisePropertyChanged("ProductID");
            }
        }
        
        /// <remarks/>
        public string ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
                this.RaisePropertyChanged("ProductType");
            }
        }
        
        /// <remarks/>
        public EnumerationOfAddonType AddonType {
            get {
                return this.addonTypeField;
            }
            set {
                this.addonTypeField = value;
                this.RaisePropertyChanged("AddonType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddonTypeSpecified {
            get {
                return this.addonTypeFieldSpecified;
            }
            set {
                this.addonTypeFieldSpecified = value;
                this.RaisePropertyChanged("AddonTypeSpecified");
            }
        }
        
        /// <remarks/>
        public string CategoryType {
            get {
                return this.categoryTypeField;
            }
            set {
                this.categoryTypeField = value;
                this.RaisePropertyChanged("CategoryType");
            }
        }
        
        /// <remarks/>
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("GroupName");
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        public int Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
                this.RaisePropertyChanged("Units");
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PriceList", IsNullable=false)]
        public PriceDetails[] PriceListings {
            get {
                return this.priceListingsField;
            }
            set {
                this.priceListingsField = value;
                this.RaisePropertyChanged("PriceListings");
            }
        }
        
        /// <remarks/>
        public SubscriptionDetails SubscriptionDetails {
            get {
                return this.subscriptionDetailsField;
            }
            set {
                this.subscriptionDetailsField = value;
                this.RaisePropertyChanged("SubscriptionDetails");
            }
        }
        
        /// <remarks/>
        public SplitPackage SplitPackageDetails {
            get {
                return this.splitPackageDetailsField;
            }
            set {
                this.splitPackageDetailsField = value;
                this.RaisePropertyChanged("SplitPackageDetails");
            }
        }
        
        /// <remarks/>
        public SplitPackage SubscriptionSplitPackageDetails {
            get {
                return this.subscriptionSplitPackageDetailsField;
            }
            set {
                this.subscriptionSplitPackageDetailsField = value;
                this.RaisePropertyChanged("SubscriptionSplitPackageDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FulfillmentModule", IsNullable=false)]
        public Module[] FulfillmentModules {
            get {
                return this.fulfillmentModulesField;
            }
            set {
                this.fulfillmentModulesField = value;
                this.RaisePropertyChanged("FulfillmentModules");
            }
        }
        
        /// <remarks/>
        public int FulfillmentBundle {
            get {
                return this.fulfillmentBundleField;
            }
            set {
                this.fulfillmentBundleField = value;
                this.RaisePropertyChanged("FulfillmentBundle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public enum EnumerationOfAddonType {
        
        /// <remarks/>
        MainSku,
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        ReportAddon,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class CompletionResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string completionCodeField;
        
        private string responseMessageField;
        
        private string responseDetailField;
        
        /// <remarks/>
        public string CompletionCode {
            get {
                return this.completionCodeField;
            }
            set {
                this.completionCodeField = value;
                this.RaisePropertyChanged("CompletionCode");
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
                this.RaisePropertyChanged("ResponseMessage");
            }
        }
        
        /// <remarks/>
        public string ResponseDetail {
            get {
                return this.responseDetailField;
            }
            set {
                this.responseDetailField = value;
                this.RaisePropertyChanged("ResponseDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class SearchCriteriaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string addressField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipCodeField;
        
        private string phoneField;
        
        private string emailAddressField;
        
        private string screenNameField;
        
        private System.DateTime dOBField;
        
        private bool dOBFieldSpecified;
        
        private string recordIDField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("MiddleName");
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        /// <remarks/>
        public string ScreenName {
            get {
                return this.screenNameField;
            }
            set {
                this.screenNameField = value;
                this.RaisePropertyChanged("ScreenName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
                this.RaisePropertyChanged("DOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DOBSpecified {
            get {
                return this.dOBFieldSpecified;
            }
            set {
                this.dOBFieldSpecified = value;
                this.RaisePropertyChanged("DOBSpecified");
            }
        }
        
        /// <remarks/>
        public string RecordID {
            get {
                return this.recordIDField;
            }
            set {
                this.recordIDField = value;
                this.RaisePropertyChanged("RecordID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class UserContextType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userTokenField;
        
        private string emailAddressField;
        
        /// <remarks/>
        public string UserToken {
            get {
                return this.userTokenField;
            }
            set {
                this.userTokenField = value;
                this.RaisePropertyChanged("UserToken");
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddons", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class GetAddonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Catalog.ClientAuthType ClientAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public int ProductID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=2)]
        public string ProductToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=3)]
        public int OrderLocation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=4)]
        public Aci.X.IwsLib.Commerce.v2_1.Catalog.UserContextType UserContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=5)]
        public Aci.X.IwsLib.Commerce.v2_1.Catalog.SearchCriteriaType SearchCriteria;
        
        public GetAddonsRequest() {
        }
        
        public GetAddonsRequest(Aci.X.IwsLib.Commerce.v2_1.Catalog.ClientAuthType ClientAuth, int ProductID, string ProductToken, int OrderLocation, Aci.X.IwsLib.Commerce.v2_1.Catalog.UserContextType UserContext, Aci.X.IwsLib.Commerce.v2_1.Catalog.SearchCriteriaType SearchCriteria) {
            this.ClientAuth = ClientAuth;
            this.ProductID = ProductID;
            this.ProductToken = ProductToken;
            this.OrderLocation = OrderLocation;
            this.UserContext = UserContext;
            this.SearchCriteria = SearchCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddonsResponse", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class GetAddonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Catalog.CompletionResponseType CompletionResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Addon", IsNullable=false)]
        public Aci.X.IwsLib.Commerce.v2_1.Catalog.Product[] Addons;
        
        public GetAddonsResponse() {
        }
        
        public GetAddonsResponse(Aci.X.IwsLib.Commerce.v2_1.Catalog.CompletionResponseType CompletionResponse, Aci.X.IwsLib.Commerce.v2_1.Catalog.Product[] Addons) {
            this.CompletionResponse = CompletionResponse;
            this.Addons = Addons;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProduct", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class GetProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Catalog.ClientAuthType ClientAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public int ProductGroupID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=2)]
        public int OrderLocation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Products", IsNullable=false)]
        public Aci.X.IwsLib.Commerce.v2_1.Catalog.ProductItemType[] ProductList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=4)]
        public Aci.X.IwsLib.Commerce.v2_1.Catalog.UserContextType UserContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=5)]
        public Aci.X.IwsLib.Commerce.v2_1.Catalog.SearchCriteriaType SearchCriteria;
        
        public GetProductRequest() {
        }
        
        public GetProductRequest(Aci.X.IwsLib.Commerce.v2_1.Catalog.ClientAuthType ClientAuth, int ProductGroupID, int OrderLocation, Aci.X.IwsLib.Commerce.v2_1.Catalog.ProductItemType[] ProductList, Aci.X.IwsLib.Commerce.v2_1.Catalog.UserContextType UserContext, Aci.X.IwsLib.Commerce.v2_1.Catalog.SearchCriteriaType SearchCriteria) {
            this.ClientAuth = ClientAuth;
            this.ProductGroupID = ProductGroupID;
            this.OrderLocation = OrderLocation;
            this.ProductList = ProductList;
            this.UserContext = UserContext;
            this.SearchCriteria = SearchCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProductResponse", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class GetProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Catalog.CompletionResponseType CompletionResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Aci.X.IwsLib.Commerce.v2_1.Catalog.Product[] Products;
        
        public GetProductResponse() {
        }
        
        public GetProductResponse(Aci.X.IwsLib.Commerce.v2_1.Catalog.CompletionResponseType CompletionResponse, Aci.X.IwsLib.Commerce.v2_1.Catalog.Product[] Products) {
            this.CompletionResponse = CompletionResponse;
            this.Products = Products;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CatalogServicesPortTypeChannel : Aci.X.IwsLib.Commerce.v2_1.Catalog.CatalogServicesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogServicesPortTypeClient : System.ServiceModel.ClientBase<Aci.X.IwsLib.Commerce.v2_1.Catalog.CatalogServicesPortType>, Aci.X.IwsLib.Commerce.v2_1.Catalog.CatalogServicesPortType {
        
        public CatalogServicesPortTypeClient() {
        }
        
        public CatalogServicesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogServicesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogServicesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogServicesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aci.X.IwsLib.Commerce.v2_1.Catalog.GetAddonsResponse Aci.X.IwsLib.Commerce.v2_1.Catalog.CatalogServicesPortType.GetAddons(Aci.X.IwsLib.Commerce.v2_1.Catalog.GetAddonsRequest request) {
            return base.Channel.GetAddons(request);
        }
        
        public Aci.X.IwsLib.Commerce.v2_1.Catalog.CompletionResponseType GetAddons(Aci.X.IwsLib.Commerce.v2_1.Catalog.ClientAuthType ClientAuth, int ProductID, string ProductToken, int OrderLocation, Aci.X.IwsLib.Commerce.v2_1.Catalog.UserContextType UserContext, Aci.X.IwsLib.Commerce.v2_1.Catalog.SearchCriteriaType SearchCriteria, out Aci.X.IwsLib.Commerce.v2_1.Catalog.Product[] Addons) {
            Aci.X.IwsLib.Commerce.v2_1.Catalog.GetAddonsRequest inValue = new Aci.X.IwsLib.Commerce.v2_1.Catalog.GetAddonsRequest();
            inValue.ClientAuth = ClientAuth;
            inValue.ProductID = ProductID;
            inValue.ProductToken = ProductToken;
            inValue.OrderLocation = OrderLocation;
            inValue.UserContext = UserContext;
            inValue.SearchCriteria = SearchCriteria;
            Aci.X.IwsLib.Commerce.v2_1.Catalog.GetAddonsResponse retVal = ((Aci.X.IwsLib.Commerce.v2_1.Catalog.CatalogServicesPortType)(this)).GetAddons(inValue);
            Addons = retVal.Addons;
            return retVal.CompletionResponse;
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Catalog.GetAddonsResponse> GetAddonsAsync(Aci.X.IwsLib.Commerce.v2_1.Catalog.GetAddonsRequest request) {
            return base.Channel.GetAddonsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aci.X.IwsLib.Commerce.v2_1.Catalog.GetProductResponse Aci.X.IwsLib.Commerce.v2_1.Catalog.CatalogServicesPortType.GetProduct(Aci.X.IwsLib.Commerce.v2_1.Catalog.GetProductRequest request) {
            return base.Channel.GetProduct(request);
        }
        
        public Aci.X.IwsLib.Commerce.v2_1.Catalog.CompletionResponseType GetProduct(Aci.X.IwsLib.Commerce.v2_1.Catalog.ClientAuthType ClientAuth, int ProductGroupID, int OrderLocation, Aci.X.IwsLib.Commerce.v2_1.Catalog.ProductItemType[] ProductList, Aci.X.IwsLib.Commerce.v2_1.Catalog.UserContextType UserContext, Aci.X.IwsLib.Commerce.v2_1.Catalog.SearchCriteriaType SearchCriteria, out Aci.X.IwsLib.Commerce.v2_1.Catalog.Product[] Products) {
            Aci.X.IwsLib.Commerce.v2_1.Catalog.GetProductRequest inValue = new Aci.X.IwsLib.Commerce.v2_1.Catalog.GetProductRequest();
            inValue.ClientAuth = ClientAuth;
            inValue.ProductGroupID = ProductGroupID;
            inValue.OrderLocation = OrderLocation;
            inValue.ProductList = ProductList;
            inValue.UserContext = UserContext;
            inValue.SearchCriteria = SearchCriteria;
            Aci.X.IwsLib.Commerce.v2_1.Catalog.GetProductResponse retVal = ((Aci.X.IwsLib.Commerce.v2_1.Catalog.CatalogServicesPortType)(this)).GetProduct(inValue);
            Products = retVal.Products;
            return retVal.CompletionResponse;
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Catalog.GetProductResponse> GetProductAsync(Aci.X.IwsLib.Commerce.v2_1.Catalog.GetProductRequest request) {
            return base.Channel.GetProductAsync(request);
        }
    }
}
