SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[spSearchResultsGetUnconsumed](@NumRows INT=1000) AS
  SET NOCOUNT ON
  SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
  SET ROWCOUNT @NumRows
  SELECT ID
    FROM SearchResults sr
    WHERE DateConsumed IS NULL
    AND EXISTS (
      SELECT ID FROM IwsCache WHERE QueryID=sr.ID
    )

GO
