//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aci.X.IwsLib.Commerce.v2_1.Customer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", ConfigurationName="Commerce.v2_1.Customer.AccountServicesPortType")]
    public interface AccountServicesPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/AuthenticateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aci.X.IwsLib.Commerce.v2_1.Customer.AuthenticateUserResponse AuthenticateUser(Aci.X.IwsLib.Commerce.v2_1.Customer.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.AuthenticateUserResponse> AuthenticateUserAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/CreateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aci.X.IwsLib.Commerce.v2_1.Customer.CreateUserResponse CreateUser(Aci.X.IwsLib.Commerce.v2_1.Customer.CreateUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/CreateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.CreateUserResponse> CreateUserAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.CreateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/IsUserExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CompletionResponse")]
        Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType IsUserExist(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string EmailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/IsUserExist", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CompletionResponse")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType> IsUserExistAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string EmailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/ResetPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aci.X.IwsLib.Commerce.v2_1.Customer.ResetPasswordResponse ResetPassword(Aci.X.IwsLib.Commerce.v2_1.Customer.ResetPasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/ResetPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.ResetPasswordResponse> ResetPasswordAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.ResetPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/UpdateCommunication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CompletionResponse")]
        Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType UpdateCommunication(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string UserToken, Aci.X.IwsLib.Commerce.v2_1.Customer.Channels Communication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/UpdateCommunication", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CompletionResponse")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType> UpdateCommunicationAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string UserToken, Aci.X.IwsLib.Commerce.v2_1.Customer.Channels Communication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/UpdatePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CompletionResponse")]
        Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType UpdatePassword(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string UserToken, string CurrentPassword, string NewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/UpdatePassword", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CompletionResponse")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType> UpdatePasswordAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string UserToken, string CurrentPassword, string NewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/UpdatePayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CompletionResponse")]
        Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType UpdatePayment(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string UserToken, Aci.X.IwsLib.Commerce.v2_1.Customer.Wallet Wallet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/UpdatePayment", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CompletionResponse")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType> UpdatePaymentAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string UserToken, Aci.X.IwsLib.Commerce.v2_1.Customer.Wallet Wallet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/UpdateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aci.X.IwsLib.Commerce.v2_1.Customer.UpdateUserResponse UpdateUser(Aci.X.IwsLib.Commerce.v2_1.Customer.UpdateUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/customer.php/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.UpdateUserResponse> UpdateUserAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.UpdateUserRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class ClientAuthType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIDField;
        
        private string authIDField;
        
        private string authKeyField;
        
        /// <remarks/>
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
                this.RaisePropertyChanged("ClientID");
            }
        }
        
        /// <remarks/>
        public string AuthID {
            get {
                return this.authIDField;
            }
            set {
                this.authIDField = value;
                this.RaisePropertyChanged("AuthID");
            }
        }
        
        /// <remarks/>
        public string AuthKey {
            get {
                return this.authKeyField;
            }
            set {
                this.authKeyField = value;
                this.RaisePropertyChanged("AuthKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class ChannelType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int channelIDField;
        
        private string channelAdWordField;
        
        private string affiliateReferenceIDField;
        
        /// <remarks/>
        public int ChannelID {
            get {
                return this.channelIDField;
            }
            set {
                this.channelIDField = value;
                this.RaisePropertyChanged("ChannelID");
            }
        }
        
        /// <remarks/>
        public string ChannelAdWord {
            get {
                return this.channelAdWordField;
            }
            set {
                this.channelAdWordField = value;
                this.RaisePropertyChanged("ChannelAdWord");
            }
        }
        
        /// <remarks/>
        public string AffiliateReferenceID {
            get {
                return this.affiliateReferenceIDField;
            }
            set {
                this.affiliateReferenceIDField = value;
                this.RaisePropertyChanged("AffiliateReferenceID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class RequestContext : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string endUserIpAddressField;
        
        private string accountListField;
        
        /// <remarks/>
        public string EndUserIpAddress {
            get {
                return this.endUserIpAddressField;
            }
            set {
                this.endUserIpAddressField = value;
                this.RaisePropertyChanged("EndUserIpAddress");
            }
        }
        
        /// <remarks/>
        public string AccountList {
            get {
                return this.accountListField;
            }
            set {
                this.accountListField = value;
                this.RaisePropertyChanged("AccountList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class CompletionResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string completionCodeField;
        
        private string responseMessageField;
        
        private string responseDetailField;
        
        /// <remarks/>
        public string CompletionCode {
            get {
                return this.completionCodeField;
            }
            set {
                this.completionCodeField = value;
                this.RaisePropertyChanged("CompletionCode");
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
                this.RaisePropertyChanged("ResponseMessage");
            }
        }
        
        /// <remarks/>
        public string ResponseDetail {
            get {
                return this.responseDetailField;
            }
            set {
                this.responseDetailField = value;
                this.RaisePropertyChanged("ResponseDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class ITunes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string uDIDField;
        
        private string referenceIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        public string UDID {
            get {
                return this.uDIDField;
            }
            set {
                this.uDIDField = value;
                this.RaisePropertyChanged("UDID");
            }
        }
        
        /// <remarks/>
        public string ReferenceId {
            get {
                return this.referenceIdField;
            }
            set {
                this.referenceIdField = value;
                this.RaisePropertyChanged("ReferenceId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class CreditCard : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private bool primaryField;
        
        private bool primaryFieldSpecified;
        
        private string numberField;
        
        private string cardTokenField;
        
        private string binNumberField;
        
        private string lastFourField;
        
        private string ownerField;
        
        private string expirationYearField;
        
        private string expirationMonthField;
        
        private string typeField;
        
        private Address billingAddressField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        public bool Primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
                this.RaisePropertyChanged("Primary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrimarySpecified {
            get {
                return this.primaryFieldSpecified;
            }
            set {
                this.primaryFieldSpecified = value;
                this.RaisePropertyChanged("PrimarySpecified");
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        public string CardToken {
            get {
                return this.cardTokenField;
            }
            set {
                this.cardTokenField = value;
                this.RaisePropertyChanged("CardToken");
            }
        }
        
        /// <remarks/>
        public string BinNumber {
            get {
                return this.binNumberField;
            }
            set {
                this.binNumberField = value;
                this.RaisePropertyChanged("BinNumber");
            }
        }
        
        /// <remarks/>
        public string LastFour {
            get {
                return this.lastFourField;
            }
            set {
                this.lastFourField = value;
                this.RaisePropertyChanged("LastFour");
            }
        }
        
        /// <remarks/>
        public string Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("Owner");
            }
        }
        
        /// <remarks/>
        public string ExpirationYear {
            get {
                return this.expirationYearField;
            }
            set {
                this.expirationYearField = value;
                this.RaisePropertyChanged("ExpirationYear");
            }
        }
        
        /// <remarks/>
        public string ExpirationMonth {
            get {
                return this.expirationMonthField;
            }
            set {
                this.expirationMonthField = value;
                this.RaisePropertyChanged("ExpirationMonth");
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        public Address BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
                this.RaisePropertyChanged("BillingAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string labelField;
        
        private bool primaryField;
        
        private bool primaryFieldSpecified;
        
        private string locationField;
        
        private string street1Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string countryField;
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("Label");
            }
        }
        
        /// <remarks/>
        public bool Primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
                this.RaisePropertyChanged("Primary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrimarySpecified {
            get {
                return this.primaryFieldSpecified;
            }
            set {
                this.primaryFieldSpecified = value;
                this.RaisePropertyChanged("PrimarySpecified");
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        public string Street1 {
            get {
                return this.street1Field;
            }
            set {
                this.street1Field = value;
                this.RaisePropertyChanged("Street1");
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class Wallet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CreditCard[] creditCardsField;
        
        private ITunes iTunesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CreditCard[] CreditCards {
            get {
                return this.creditCardsField;
            }
            set {
                this.creditCardsField = value;
                this.RaisePropertyChanged("CreditCards");
            }
        }
        
        /// <remarks/>
        public ITunes ITunes {
            get {
                return this.iTunesField;
            }
            set {
                this.iTunesField = value;
                this.RaisePropertyChanged("ITunes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class Agreement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string nameField;
        
        private System.DateTime acceptedDateField;
        
        private bool acceptedDateFieldSpecified;
        
        private System.DateTime approvalDateField;
        
        private bool approvalDateFieldSpecified;
        
        private string approvedByField;
        
        private System.DateTime expirationDateField;
        
        private bool expirationDateFieldSpecified;
        
        private string signatureField;
        
        private string statusField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime AcceptedDate {
            get {
                return this.acceptedDateField;
            }
            set {
                this.acceptedDateField = value;
                this.RaisePropertyChanged("AcceptedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AcceptedDateSpecified {
            get {
                return this.acceptedDateFieldSpecified;
            }
            set {
                this.acceptedDateFieldSpecified = value;
                this.RaisePropertyChanged("AcceptedDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ApprovalDate {
            get {
                return this.approvalDateField;
            }
            set {
                this.approvalDateField = value;
                this.RaisePropertyChanged("ApprovalDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApprovalDateSpecified {
            get {
                return this.approvalDateFieldSpecified;
            }
            set {
                this.approvalDateFieldSpecified = value;
                this.RaisePropertyChanged("ApprovalDateSpecified");
            }
        }
        
        /// <remarks/>
        public string ApprovedBy {
            get {
                return this.approvedByField;
            }
            set {
                this.approvedByField = value;
                this.RaisePropertyChanged("ApprovedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpirationDateSpecified {
            get {
                return this.expirationDateFieldSpecified;
            }
            set {
                this.expirationDateFieldSpecified = value;
                this.RaisePropertyChanged("ExpirationDateSpecified");
            }
        }
        
        /// <remarks/>
        public string Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("Signature");
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class Preference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class WebUrl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string labelField;
        
        private bool primaryField;
        
        private bool primaryFieldSpecified;
        
        private string locationField;
        
        private string addressField;
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("Label");
            }
        }
        
        /// <remarks/>
        public bool Primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
                this.RaisePropertyChanged("Primary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrimarySpecified {
            get {
                return this.primaryFieldSpecified;
            }
            set {
                this.primaryFieldSpecified = value;
                this.RaisePropertyChanged("PrimarySpecified");
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class Phone : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string labelField;
        
        private bool primaryField;
        
        private bool primaryFieldSpecified;
        
        private string locationField;
        
        private string numberField;
        
        private string extensionField;
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("Label");
            }
        }
        
        /// <remarks/>
        public bool Primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
                this.RaisePropertyChanged("Primary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrimarySpecified {
            get {
                return this.primaryFieldSpecified;
            }
            set {
                this.primaryFieldSpecified = value;
                this.RaisePropertyChanged("PrimarySpecified");
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("Extension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class Email : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string labelField;
        
        private bool primaryField;
        
        private bool primaryFieldSpecified;
        
        private string locationField;
        
        private string addressField;
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("Label");
            }
        }
        
        /// <remarks/>
        public bool Primary {
            get {
                return this.primaryField;
            }
            set {
                this.primaryField = value;
                this.RaisePropertyChanged("Primary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrimarySpecified {
            get {
                return this.primaryFieldSpecified;
            }
            set {
                this.primaryFieldSpecified = value;
                this.RaisePropertyChanged("PrimarySpecified");
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class Channels : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Email[] emailsField;
        
        private Address[] addressesField;
        
        private Phone[] phonesField;
        
        private WebUrl[] urlsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Email[] Emails {
            get {
                return this.emailsField;
            }
            set {
                this.emailsField = value;
                this.RaisePropertyChanged("Emails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Address[] Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("Addresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Phone[] Phones {
            get {
                return this.phonesField;
            }
            set {
                this.phonesField = value;
                this.RaisePropertyChanged("Phones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WebUrl[] Urls {
            get {
                return this.urlsField;
            }
            set {
                this.urlsField = value;
                this.RaisePropertyChanged("Urls");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class Login : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private string firstIpField;
        
        private string lastIpField;
        
        private System.DateTime dateLastLoginField;
        
        private bool dateLastLoginFieldSpecified;
        
        private string tempPasswordField;
        
        private System.DateTime passwordExpireField;
        
        private bool passwordExpireFieldSpecified;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        public string FirstIp {
            get {
                return this.firstIpField;
            }
            set {
                this.firstIpField = value;
                this.RaisePropertyChanged("FirstIp");
            }
        }
        
        /// <remarks/>
        public string LastIp {
            get {
                return this.lastIpField;
            }
            set {
                this.lastIpField = value;
                this.RaisePropertyChanged("LastIp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateLastLogin {
            get {
                return this.dateLastLoginField;
            }
            set {
                this.dateLastLoginField = value;
                this.RaisePropertyChanged("DateLastLogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateLastLoginSpecified {
            get {
                return this.dateLastLoginFieldSpecified;
            }
            set {
                this.dateLastLoginFieldSpecified = value;
                this.RaisePropertyChanged("DateLastLoginSpecified");
            }
        }
        
        /// <remarks/>
        public string TempPassword {
            get {
                return this.tempPasswordField;
            }
            set {
                this.tempPasswordField = value;
                this.RaisePropertyChanged("TempPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PasswordExpire {
            get {
                return this.passwordExpireField;
            }
            set {
                this.passwordExpireField = value;
                this.RaisePropertyChanged("PasswordExpire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PasswordExpireSpecified {
            get {
                return this.passwordExpireFieldSpecified;
            }
            set {
                this.passwordExpireFieldSpecified = value;
                this.RaisePropertyChanged("PasswordExpireSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int userIDField;
        
        private bool userIDFieldSpecified;
        
        private string userTokenField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private System.DateTime dateCreatedField;
        
        private bool dateCreatedFieldSpecified;
        
        private bool activeField;
        
        private bool activeFieldSpecified;
        
        private Login loginField;
        
        private Channels channelsField;
        
        private Preference[] userPreferencesField;
        
        private Agreement[] userAgreementsField;
        
        private Wallet walletField;
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserIDSpecified {
            get {
                return this.userIDFieldSpecified;
            }
            set {
                this.userIDFieldSpecified = value;
                this.RaisePropertyChanged("UserIDSpecified");
            }
        }
        
        /// <remarks/>
        public string UserToken {
            get {
                return this.userTokenField;
            }
            set {
                this.userTokenField = value;
                this.RaisePropertyChanged("UserToken");
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
                this.RaisePropertyChanged("DateCreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateCreatedSpecified {
            get {
                return this.dateCreatedFieldSpecified;
            }
            set {
                this.dateCreatedFieldSpecified = value;
                this.RaisePropertyChanged("DateCreatedSpecified");
            }
        }
        
        /// <remarks/>
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActiveSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
                this.RaisePropertyChanged("ActiveSpecified");
            }
        }
        
        /// <remarks/>
        public Login Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("Login");
            }
        }
        
        /// <remarks/>
        public Channels Channels {
            get {
                return this.channelsField;
            }
            set {
                this.channelsField = value;
                this.RaisePropertyChanged("Channels");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Preference[] UserPreferences {
            get {
                return this.userPreferencesField;
            }
            set {
                this.userPreferencesField = value;
                this.RaisePropertyChanged("UserPreferences");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Agreement[] UserAgreements {
            get {
                return this.userAgreementsField;
            }
            set {
                this.userAgreementsField = value;
                this.RaisePropertyChanged("UserAgreements");
            }
        }
        
        /// <remarks/>
        public Wallet Wallet {
            get {
                return this.walletField;
            }
            set {
                this.walletField = value;
                this.RaisePropertyChanged("Wallet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class LoginRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private string remoteIpField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        public string RemoteIp {
            get {
                return this.remoteIpField;
            }
            set {
                this.remoteIpField = value;
                this.RaisePropertyChanged("RemoteIp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUser", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.LoginRequest LoginRequest;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, Aci.X.IwsLib.Commerce.v2_1.Customer.LoginRequest LoginRequest) {
            this.ClientAuth = ClientAuth;
            this.LoginRequest = LoginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUserResponse", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.User User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType CompletionResponse;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(Aci.X.IwsLib.Commerce.v2_1.Customer.User User, Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType CompletionResponse) {
            this.User = User;
            this.CompletionResponse = CompletionResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUser", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.RequestContext RequestContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=2)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.ChannelType Channel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=3)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.User User;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, Aci.X.IwsLib.Commerce.v2_1.Customer.RequestContext RequestContext, Aci.X.IwsLib.Commerce.v2_1.Customer.ChannelType Channel, Aci.X.IwsLib.Commerce.v2_1.Customer.User User) {
            this.ClientAuth = ClientAuth;
            this.RequestContext = RequestContext;
            this.Channel = Channel;
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUserResponse", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public string UserToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType CompletionResponse;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(string UserToken, Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType CompletionResponse) {
            this.UserToken = UserToken;
            this.CompletionResponse = CompletionResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetPassword", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class ResetPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public string EmailAddress;
        
        public ResetPasswordRequest() {
        }
        
        public ResetPasswordRequest(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string EmailAddress) {
            this.ClientAuth = ClientAuth;
            this.EmailAddress = EmailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetPasswordResponse", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class ResetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public string TemporaryPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType CompletionResponse;
        
        public ResetPasswordResponse() {
        }
        
        public ResetPasswordResponse(string TemporaryPassword, Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType CompletionResponse) {
            this.TemporaryPassword = TemporaryPassword;
            this.CompletionResponse = CompletionResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUser", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.User User;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, Aci.X.IwsLib.Commerce.v2_1.Customer.User User) {
            this.ClientAuth = ClientAuth;
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUserResponse", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.User User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType CompletionResponse;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(Aci.X.IwsLib.Commerce.v2_1.Customer.User User, Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType CompletionResponse) {
            this.User = User;
            this.CompletionResponse = CompletionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountServicesPortTypeChannel : Aci.X.IwsLib.Commerce.v2_1.Customer.AccountServicesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServicesPortTypeClient : System.ServiceModel.ClientBase<Aci.X.IwsLib.Commerce.v2_1.Customer.AccountServicesPortType>, Aci.X.IwsLib.Commerce.v2_1.Customer.AccountServicesPortType {
        
        public AccountServicesPortTypeClient() {
        }
        
        public AccountServicesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServicesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServicesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServicesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aci.X.IwsLib.Commerce.v2_1.Customer.AuthenticateUserResponse Aci.X.IwsLib.Commerce.v2_1.Customer.AccountServicesPortType.AuthenticateUser(Aci.X.IwsLib.Commerce.v2_1.Customer.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public Aci.X.IwsLib.Commerce.v2_1.Customer.User AuthenticateUser(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, Aci.X.IwsLib.Commerce.v2_1.Customer.LoginRequest LoginRequest, out Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType CompletionResponse) {
            Aci.X.IwsLib.Commerce.v2_1.Customer.AuthenticateUserRequest inValue = new Aci.X.IwsLib.Commerce.v2_1.Customer.AuthenticateUserRequest();
            inValue.ClientAuth = ClientAuth;
            inValue.LoginRequest = LoginRequest;
            Aci.X.IwsLib.Commerce.v2_1.Customer.AuthenticateUserResponse retVal = ((Aci.X.IwsLib.Commerce.v2_1.Customer.AccountServicesPortType)(this)).AuthenticateUser(inValue);
            CompletionResponse = retVal.CompletionResponse;
            return retVal.User;
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.AuthenticateUserResponse> AuthenticateUserAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aci.X.IwsLib.Commerce.v2_1.Customer.CreateUserResponse Aci.X.IwsLib.Commerce.v2_1.Customer.AccountServicesPortType.CreateUser(Aci.X.IwsLib.Commerce.v2_1.Customer.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public string CreateUser(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, Aci.X.IwsLib.Commerce.v2_1.Customer.RequestContext RequestContext, Aci.X.IwsLib.Commerce.v2_1.Customer.ChannelType Channel, Aci.X.IwsLib.Commerce.v2_1.Customer.User User, out Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType CompletionResponse) {
            Aci.X.IwsLib.Commerce.v2_1.Customer.CreateUserRequest inValue = new Aci.X.IwsLib.Commerce.v2_1.Customer.CreateUserRequest();
            inValue.ClientAuth = ClientAuth;
            inValue.RequestContext = RequestContext;
            inValue.Channel = Channel;
            inValue.User = User;
            Aci.X.IwsLib.Commerce.v2_1.Customer.CreateUserResponse retVal = ((Aci.X.IwsLib.Commerce.v2_1.Customer.AccountServicesPortType)(this)).CreateUser(inValue);
            CompletionResponse = retVal.CompletionResponse;
            return retVal.UserToken;
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.CreateUserResponse> CreateUserAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.CreateUserRequest request) {
            return base.Channel.CreateUserAsync(request);
        }
        
        public Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType IsUserExist(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string EmailAddress) {
            return base.Channel.IsUserExist(ClientAuth, EmailAddress);
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType> IsUserExistAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string EmailAddress) {
            return base.Channel.IsUserExistAsync(ClientAuth, EmailAddress);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aci.X.IwsLib.Commerce.v2_1.Customer.ResetPasswordResponse Aci.X.IwsLib.Commerce.v2_1.Customer.AccountServicesPortType.ResetPassword(Aci.X.IwsLib.Commerce.v2_1.Customer.ResetPasswordRequest request) {
            return base.Channel.ResetPassword(request);
        }
        
        public string ResetPassword(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string EmailAddress, out Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType CompletionResponse) {
            Aci.X.IwsLib.Commerce.v2_1.Customer.ResetPasswordRequest inValue = new Aci.X.IwsLib.Commerce.v2_1.Customer.ResetPasswordRequest();
            inValue.ClientAuth = ClientAuth;
            inValue.EmailAddress = EmailAddress;
            Aci.X.IwsLib.Commerce.v2_1.Customer.ResetPasswordResponse retVal = ((Aci.X.IwsLib.Commerce.v2_1.Customer.AccountServicesPortType)(this)).ResetPassword(inValue);
            CompletionResponse = retVal.CompletionResponse;
            return retVal.TemporaryPassword;
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.ResetPasswordResponse> ResetPasswordAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.ResetPasswordRequest request) {
            return base.Channel.ResetPasswordAsync(request);
        }
        
        public Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType UpdateCommunication(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string UserToken, Aci.X.IwsLib.Commerce.v2_1.Customer.Channels Communication) {
            return base.Channel.UpdateCommunication(ClientAuth, UserToken, Communication);
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType> UpdateCommunicationAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string UserToken, Aci.X.IwsLib.Commerce.v2_1.Customer.Channels Communication) {
            return base.Channel.UpdateCommunicationAsync(ClientAuth, UserToken, Communication);
        }
        
        public Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType UpdatePassword(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string UserToken, string CurrentPassword, string NewPassword) {
            return base.Channel.UpdatePassword(ClientAuth, UserToken, CurrentPassword, NewPassword);
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType> UpdatePasswordAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string UserToken, string CurrentPassword, string NewPassword) {
            return base.Channel.UpdatePasswordAsync(ClientAuth, UserToken, CurrentPassword, NewPassword);
        }
        
        public Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType UpdatePayment(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string UserToken, Aci.X.IwsLib.Commerce.v2_1.Customer.Wallet Wallet) {
            return base.Channel.UpdatePayment(ClientAuth, UserToken, Wallet);
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType> UpdatePaymentAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, string UserToken, Aci.X.IwsLib.Commerce.v2_1.Customer.Wallet Wallet) {
            return base.Channel.UpdatePaymentAsync(ClientAuth, UserToken, Wallet);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aci.X.IwsLib.Commerce.v2_1.Customer.UpdateUserResponse Aci.X.IwsLib.Commerce.v2_1.Customer.AccountServicesPortType.UpdateUser(Aci.X.IwsLib.Commerce.v2_1.Customer.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public Aci.X.IwsLib.Commerce.v2_1.Customer.CompletionResponseType UpdateUser(Aci.X.IwsLib.Commerce.v2_1.Customer.ClientAuthType ClientAuth, ref Aci.X.IwsLib.Commerce.v2_1.Customer.User User) {
            Aci.X.IwsLib.Commerce.v2_1.Customer.UpdateUserRequest inValue = new Aci.X.IwsLib.Commerce.v2_1.Customer.UpdateUserRequest();
            inValue.ClientAuth = ClientAuth;
            inValue.User = User;
            Aci.X.IwsLib.Commerce.v2_1.Customer.UpdateUserResponse retVal = ((Aci.X.IwsLib.Commerce.v2_1.Customer.AccountServicesPortType)(this)).UpdateUser(inValue);
            User = retVal.User;
            return retVal.CompletionResponse;
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Customer.UpdateUserResponse> UpdateUserAsync(Aci.X.IwsLib.Commerce.v2_1.Customer.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
    }
}
