SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[InteliusAdmin] (
		[EmailAddress]     [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[InteliusAdmin]
	ADD
	CONSTRAINT [PK_InteliusAdmins]
	PRIMARY KEY
	CLUSTERED
	([EmailAddress])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[InteliusAdmin] SET (LOCK_ESCALATION = TABLE)
GO
