SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Domain] (
		[ID]             [int] IDENTITY(1, 1) NOT NULL,
		[DomainName]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Domain]
	ADD
	CONSTRAINT [PK_Domain]
	PRIMARY KEY
	CLUSTERED
	([ID])
	ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Domain]
	ON [dbo].[Domain] ([DomainName])
	INCLUDE ([ID])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[Domain] SET (LOCK_ESCALATION = TABLE)
GO
