SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION fnHashModString(@Divisor INT, @String VARCHAR(MAX)) RETURNS INT AS
BEGIN
  RETURN ABS(CONVERT(INT,HASHBYTES('SHA1',@String))) % @Divisor
END
GO
