CREATE TABLE [dbo].[Tally]
(
[N] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tally] ADD CONSTRAINT [PK_Tally_N] PRIMARY KEY CLUSTERED  ([N]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
