//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aci.X.IwsLib.Commerce.v2_1.Subscription {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", ConfigurationName="Commerce.v2_1.Subscription.SubscriptionServicesPortType")]
    public interface SubscriptionServicesPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/subscription.php/CancelSubscription", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aci.X.IwsLib.Commerce.v2_1.Subscription.CancelSubscriptionResponse CancelSubscription(Aci.X.IwsLib.Commerce.v2_1.Subscription.CancelSubscriptionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/subscription.php/CancelSubscription", ReplyAction="*")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Subscription.CancelSubscriptionResponse> CancelSubscriptionAsync(Aci.X.IwsLib.Commerce.v2_1.Subscription.CancelSubscriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/subscription.php/GetSubscriptionDeta" +
            "il", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aci.X.IwsLib.Commerce.v2_1.Subscription.GetSubscriptionDetailResponse GetSubscriptionDetail(Aci.X.IwsLib.Commerce.v2_1.Subscription.GetSubscriptionDetailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/subscription.php/GetSubscriptionDeta" +
            "il", ReplyAction="*")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Subscription.GetSubscriptionDetailResponse> GetSubscriptionDetailAsync(Aci.X.IwsLib.Commerce.v2_1.Subscription.GetSubscriptionDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/subscription.php/GetUserSubscription" +
            "s", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aci.X.IwsLib.Commerce.v2_1.Subscription.GetUserSubscriptionsResponse GetUserSubscriptions(Aci.X.IwsLib.Commerce.v2_1.Subscription.GetUserSubscriptionsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/subscription.php/GetUserSubscription" +
            "s", ReplyAction="*")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Subscription.GetUserSubscriptionsResponse> GetUserSubscriptionsAsync(Aci.X.IwsLib.Commerce.v2_1.Subscription.GetUserSubscriptionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/subscription.php/ReActivateSubscript" +
            "ion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aci.X.IwsLib.Commerce.v2_1.Subscription.ReActivateSubscriptionResponse ReActivateSubscription(Aci.X.IwsLib.Commerce.v2_1.Subscription.ReActivateSubscriptionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://iwscommerce.intelius.com/commerce/2.1/subscription.php/ReActivateSubscript" +
            "ion", ReplyAction="*")]
        System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Subscription.ReActivateSubscriptionResponse> ReActivateSubscriptionAsync(Aci.X.IwsLib.Commerce.v2_1.Subscription.ReActivateSubscriptionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class ClientAuthType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIDField;
        
        private string authIDField;
        
        private string authKeyField;
        
        /// <remarks/>
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
                this.RaisePropertyChanged("ClientID");
            }
        }
        
        /// <remarks/>
        public string AuthID {
            get {
                return this.authIDField;
            }
            set {
                this.authIDField = value;
                this.RaisePropertyChanged("AuthID");
            }
        }
        
        /// <remarks/>
        public string AuthKey {
            get {
                return this.authKeyField;
            }
            set {
                this.authKeyField = value;
                this.RaisePropertyChanged("AuthKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class PeriodType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int periodIDField;
        
        private int serviceGroupIDField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private string previousPeriodIDField;
        
        private string statusCodeField;
        
        private string statusField;
        
        private string trialField;
        
        private int periodOrderIDField;
        
        /// <remarks/>
        public int PeriodID {
            get {
                return this.periodIDField;
            }
            set {
                this.periodIDField = value;
                this.RaisePropertyChanged("PeriodID");
            }
        }
        
        /// <remarks/>
        public int ServiceGroupID {
            get {
                return this.serviceGroupIDField;
            }
            set {
                this.serviceGroupIDField = value;
                this.RaisePropertyChanged("ServiceGroupID");
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        public string PreviousPeriodID {
            get {
                return this.previousPeriodIDField;
            }
            set {
                this.previousPeriodIDField = value;
                this.RaisePropertyChanged("PreviousPeriodID");
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        public string Trial {
            get {
                return this.trialField;
            }
            set {
                this.trialField = value;
                this.RaisePropertyChanged("Trial");
            }
        }
        
        /// <remarks/>
        public int PeriodOrderID {
            get {
                return this.periodOrderIDField;
            }
            set {
                this.periodOrderIDField = value;
                this.RaisePropertyChanged("PeriodOrderID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class SubcriptionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int subscriptionIDField;
        
        private int serviceIDField;
        
        private int userIDField;
        
        private string subscriptionNameField;
        
        private System.DateTime enrollmentDateField;
        
        private string statusField;
        
        private string statusCodeField;
        
        private System.DateTime statusChangeDateField;
        
        private PeriodType[] periodsField;
        
        /// <remarks/>
        public int SubscriptionID {
            get {
                return this.subscriptionIDField;
            }
            set {
                this.subscriptionIDField = value;
                this.RaisePropertyChanged("SubscriptionID");
            }
        }
        
        /// <remarks/>
        public int ServiceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
                this.RaisePropertyChanged("ServiceID");
            }
        }
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        public string SubscriptionName {
            get {
                return this.subscriptionNameField;
            }
            set {
                this.subscriptionNameField = value;
                this.RaisePropertyChanged("SubscriptionName");
            }
        }
        
        /// <remarks/>
        public System.DateTime EnrollmentDate {
            get {
                return this.enrollmentDateField;
            }
            set {
                this.enrollmentDateField = value;
                this.RaisePropertyChanged("EnrollmentDate");
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        public System.DateTime StatusChangeDate {
            get {
                return this.statusChangeDateField;
            }
            set {
                this.statusChangeDateField = value;
                this.RaisePropertyChanged("StatusChangeDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Period", IsNullable=false)]
        public PeriodType[] Periods {
            get {
                return this.periodsField;
            }
            set {
                this.periodsField = value;
                this.RaisePropertyChanged("Periods");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class CompletionResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string completionCodeField;
        
        private string responseMessageField;
        
        private string responseDetailField;
        
        /// <remarks/>
        public string CompletionCode {
            get {
                return this.completionCodeField;
            }
            set {
                this.completionCodeField = value;
                this.RaisePropertyChanged("CompletionCode");
            }
        }
        
        /// <remarks/>
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
                this.RaisePropertyChanged("ResponseMessage");
            }
        }
        
        /// <remarks/>
        public string ResponseDetail {
            get {
                return this.responseDetailField;
            }
            set {
                this.responseDetailField = value;
                this.RaisePropertyChanged("ResponseDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public partial class UserContextType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userTokenField;
        
        private string emailAddressField;
        
        /// <remarks/>
        public string UserToken {
            get {
                return this.userTokenField;
            }
            set {
                this.userTokenField = value;
                this.RaisePropertyChanged("UserToken");
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl")]
    public enum EnumerationOfReasonCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("User Initiated")]
        UserInitiated,
        
        /// <remarks/>
        Error,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelSubscription", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class CancelSubscriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.ClientAuthType ClientAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.UserContextType UserContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=2)]
        public int SubscriptionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=3)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.EnumerationOfReasonCode ReasonCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=4)]
        public string CancelledByUserID;
        
        public CancelSubscriptionRequest() {
        }
        
        public CancelSubscriptionRequest(Aci.X.IwsLib.Commerce.v2_1.Subscription.ClientAuthType ClientAuth, Aci.X.IwsLib.Commerce.v2_1.Subscription.UserContextType UserContext, int SubscriptionID, Aci.X.IwsLib.Commerce.v2_1.Subscription.EnumerationOfReasonCode ReasonCode, string CancelledByUserID) {
            this.ClientAuth = ClientAuth;
            this.UserContext = UserContext;
            this.SubscriptionID = SubscriptionID;
            this.ReasonCode = ReasonCode;
            this.CancelledByUserID = CancelledByUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelSubscriptionResponse", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class CancelSubscriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public string RequestReferenceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.CompletionResponseType CompletionResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=2)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.SubcriptionType Subscription;
        
        public CancelSubscriptionResponse() {
        }
        
        public CancelSubscriptionResponse(string RequestReferenceID, Aci.X.IwsLib.Commerce.v2_1.Subscription.CompletionResponseType CompletionResponse, Aci.X.IwsLib.Commerce.v2_1.Subscription.SubcriptionType Subscription) {
            this.RequestReferenceID = RequestReferenceID;
            this.CompletionResponse = CompletionResponse;
            this.Subscription = Subscription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubscriptionDetail", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class GetSubscriptionDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.ClientAuthType ClientAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.UserContextType UserContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=2)]
        public int SubscriptionID;
        
        public GetSubscriptionDetailRequest() {
        }
        
        public GetSubscriptionDetailRequest(Aci.X.IwsLib.Commerce.v2_1.Subscription.ClientAuthType ClientAuth, Aci.X.IwsLib.Commerce.v2_1.Subscription.UserContextType UserContext, int SubscriptionID) {
            this.ClientAuth = ClientAuth;
            this.UserContext = UserContext;
            this.SubscriptionID = SubscriptionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubscriptionDetailResponse", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class GetSubscriptionDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public string RequestReferenceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.CompletionResponseType CompletionResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=2)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.SubcriptionType Subscription;
        
        public GetSubscriptionDetailResponse() {
        }
        
        public GetSubscriptionDetailResponse(string RequestReferenceID, Aci.X.IwsLib.Commerce.v2_1.Subscription.CompletionResponseType CompletionResponse, Aci.X.IwsLib.Commerce.v2_1.Subscription.SubcriptionType Subscription) {
            this.RequestReferenceID = RequestReferenceID;
            this.CompletionResponse = CompletionResponse;
            this.Subscription = Subscription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserSubscriptions", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class GetUserSubscriptionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.ClientAuthType ClientAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.UserContextType UserContext;
        
        public GetUserSubscriptionsRequest() {
        }
        
        public GetUserSubscriptionsRequest(Aci.X.IwsLib.Commerce.v2_1.Subscription.ClientAuthType ClientAuth, Aci.X.IwsLib.Commerce.v2_1.Subscription.UserContextType UserContext) {
            this.ClientAuth = ClientAuth;
            this.UserContext = UserContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserSubscriptionsResponse", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class GetUserSubscriptionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public string RequestReferenceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.CompletionResponseType CompletionResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Subscription", IsNullable=false)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.SubcriptionType[] Subscriptions;
        
        public GetUserSubscriptionsResponse() {
        }
        
        public GetUserSubscriptionsResponse(string RequestReferenceID, Aci.X.IwsLib.Commerce.v2_1.Subscription.CompletionResponseType CompletionResponse, Aci.X.IwsLib.Commerce.v2_1.Subscription.SubcriptionType[] Subscriptions) {
            this.RequestReferenceID = RequestReferenceID;
            this.CompletionResponse = CompletionResponse;
            this.Subscriptions = Subscriptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReActivateSubscription", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class ReActivateSubscriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.ClientAuthType ClientAuth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.UserContextType UserContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=2)]
        public int SubscriptionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=3)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.EnumerationOfReasonCode ReasonCode;
        
        public ReActivateSubscriptionRequest() {
        }
        
        public ReActivateSubscriptionRequest(Aci.X.IwsLib.Commerce.v2_1.Subscription.ClientAuthType ClientAuth, Aci.X.IwsLib.Commerce.v2_1.Subscription.UserContextType UserContext, int SubscriptionID, Aci.X.IwsLib.Commerce.v2_1.Subscription.EnumerationOfReasonCode ReasonCode) {
            this.ClientAuth = ClientAuth;
            this.UserContext = UserContext;
            this.SubscriptionID = SubscriptionID;
            this.ReasonCode = ReasonCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReActivateSubscriptionResponse", WrapperNamespace="https://api.intelius.com/commerce/2.1/wsdl", IsWrapped=true)]
    public partial class ReActivateSubscriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=0)]
        public string RequestReferenceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=1)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.CompletionResponseType CompletionResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.intelius.com/commerce/2.1/wsdl", Order=2)]
        public Aci.X.IwsLib.Commerce.v2_1.Subscription.SubcriptionType Subscription;
        
        public ReActivateSubscriptionResponse() {
        }
        
        public ReActivateSubscriptionResponse(string RequestReferenceID, Aci.X.IwsLib.Commerce.v2_1.Subscription.CompletionResponseType CompletionResponse, Aci.X.IwsLib.Commerce.v2_1.Subscription.SubcriptionType Subscription) {
            this.RequestReferenceID = RequestReferenceID;
            this.CompletionResponse = CompletionResponse;
            this.Subscription = Subscription;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubscriptionServicesPortTypeChannel : Aci.X.IwsLib.Commerce.v2_1.Subscription.SubscriptionServicesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubscriptionServicesPortTypeClient : System.ServiceModel.ClientBase<Aci.X.IwsLib.Commerce.v2_1.Subscription.SubscriptionServicesPortType>, Aci.X.IwsLib.Commerce.v2_1.Subscription.SubscriptionServicesPortType {
        
        public SubscriptionServicesPortTypeClient() {
        }
        
        public SubscriptionServicesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubscriptionServicesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriptionServicesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriptionServicesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aci.X.IwsLib.Commerce.v2_1.Subscription.CancelSubscriptionResponse Aci.X.IwsLib.Commerce.v2_1.Subscription.SubscriptionServicesPortType.CancelSubscription(Aci.X.IwsLib.Commerce.v2_1.Subscription.CancelSubscriptionRequest request) {
            return base.Channel.CancelSubscription(request);
        }
        
        public string CancelSubscription(Aci.X.IwsLib.Commerce.v2_1.Subscription.ClientAuthType ClientAuth, Aci.X.IwsLib.Commerce.v2_1.Subscription.UserContextType UserContext, int SubscriptionID, Aci.X.IwsLib.Commerce.v2_1.Subscription.EnumerationOfReasonCode ReasonCode, string CancelledByUserID, out Aci.X.IwsLib.Commerce.v2_1.Subscription.CompletionResponseType CompletionResponse, out Aci.X.IwsLib.Commerce.v2_1.Subscription.SubcriptionType Subscription) {
            Aci.X.IwsLib.Commerce.v2_1.Subscription.CancelSubscriptionRequest inValue = new Aci.X.IwsLib.Commerce.v2_1.Subscription.CancelSubscriptionRequest();
            inValue.ClientAuth = ClientAuth;
            inValue.UserContext = UserContext;
            inValue.SubscriptionID = SubscriptionID;
            inValue.ReasonCode = ReasonCode;
            inValue.CancelledByUserID = CancelledByUserID;
            Aci.X.IwsLib.Commerce.v2_1.Subscription.CancelSubscriptionResponse retVal = ((Aci.X.IwsLib.Commerce.v2_1.Subscription.SubscriptionServicesPortType)(this)).CancelSubscription(inValue);
            CompletionResponse = retVal.CompletionResponse;
            Subscription = retVal.Subscription;
            return retVal.RequestReferenceID;
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Subscription.CancelSubscriptionResponse> CancelSubscriptionAsync(Aci.X.IwsLib.Commerce.v2_1.Subscription.CancelSubscriptionRequest request) {
            return base.Channel.CancelSubscriptionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aci.X.IwsLib.Commerce.v2_1.Subscription.GetSubscriptionDetailResponse Aci.X.IwsLib.Commerce.v2_1.Subscription.SubscriptionServicesPortType.GetSubscriptionDetail(Aci.X.IwsLib.Commerce.v2_1.Subscription.GetSubscriptionDetailRequest request) {
            return base.Channel.GetSubscriptionDetail(request);
        }
        
        public string GetSubscriptionDetail(Aci.X.IwsLib.Commerce.v2_1.Subscription.ClientAuthType ClientAuth, Aci.X.IwsLib.Commerce.v2_1.Subscription.UserContextType UserContext, int SubscriptionID, out Aci.X.IwsLib.Commerce.v2_1.Subscription.CompletionResponseType CompletionResponse, out Aci.X.IwsLib.Commerce.v2_1.Subscription.SubcriptionType Subscription) {
            Aci.X.IwsLib.Commerce.v2_1.Subscription.GetSubscriptionDetailRequest inValue = new Aci.X.IwsLib.Commerce.v2_1.Subscription.GetSubscriptionDetailRequest();
            inValue.ClientAuth = ClientAuth;
            inValue.UserContext = UserContext;
            inValue.SubscriptionID = SubscriptionID;
            Aci.X.IwsLib.Commerce.v2_1.Subscription.GetSubscriptionDetailResponse retVal = ((Aci.X.IwsLib.Commerce.v2_1.Subscription.SubscriptionServicesPortType)(this)).GetSubscriptionDetail(inValue);
            CompletionResponse = retVal.CompletionResponse;
            Subscription = retVal.Subscription;
            return retVal.RequestReferenceID;
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Subscription.GetSubscriptionDetailResponse> GetSubscriptionDetailAsync(Aci.X.IwsLib.Commerce.v2_1.Subscription.GetSubscriptionDetailRequest request) {
            return base.Channel.GetSubscriptionDetailAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aci.X.IwsLib.Commerce.v2_1.Subscription.GetUserSubscriptionsResponse Aci.X.IwsLib.Commerce.v2_1.Subscription.SubscriptionServicesPortType.GetUserSubscriptions(Aci.X.IwsLib.Commerce.v2_1.Subscription.GetUserSubscriptionsRequest request) {
            return base.Channel.GetUserSubscriptions(request);
        }
        
        public string GetUserSubscriptions(Aci.X.IwsLib.Commerce.v2_1.Subscription.ClientAuthType ClientAuth, Aci.X.IwsLib.Commerce.v2_1.Subscription.UserContextType UserContext, out Aci.X.IwsLib.Commerce.v2_1.Subscription.CompletionResponseType CompletionResponse, out Aci.X.IwsLib.Commerce.v2_1.Subscription.SubcriptionType[] Subscriptions) {
            Aci.X.IwsLib.Commerce.v2_1.Subscription.GetUserSubscriptionsRequest inValue = new Aci.X.IwsLib.Commerce.v2_1.Subscription.GetUserSubscriptionsRequest();
            inValue.ClientAuth = ClientAuth;
            inValue.UserContext = UserContext;
            Aci.X.IwsLib.Commerce.v2_1.Subscription.GetUserSubscriptionsResponse retVal = ((Aci.X.IwsLib.Commerce.v2_1.Subscription.SubscriptionServicesPortType)(this)).GetUserSubscriptions(inValue);
            CompletionResponse = retVal.CompletionResponse;
            Subscriptions = retVal.Subscriptions;
            return retVal.RequestReferenceID;
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Subscription.GetUserSubscriptionsResponse> GetUserSubscriptionsAsync(Aci.X.IwsLib.Commerce.v2_1.Subscription.GetUserSubscriptionsRequest request) {
            return base.Channel.GetUserSubscriptionsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aci.X.IwsLib.Commerce.v2_1.Subscription.ReActivateSubscriptionResponse Aci.X.IwsLib.Commerce.v2_1.Subscription.SubscriptionServicesPortType.ReActivateSubscription(Aci.X.IwsLib.Commerce.v2_1.Subscription.ReActivateSubscriptionRequest request) {
            return base.Channel.ReActivateSubscription(request);
        }
        
        public string ReActivateSubscription(Aci.X.IwsLib.Commerce.v2_1.Subscription.ClientAuthType ClientAuth, Aci.X.IwsLib.Commerce.v2_1.Subscription.UserContextType UserContext, int SubscriptionID, Aci.X.IwsLib.Commerce.v2_1.Subscription.EnumerationOfReasonCode ReasonCode, out Aci.X.IwsLib.Commerce.v2_1.Subscription.CompletionResponseType CompletionResponse, out Aci.X.IwsLib.Commerce.v2_1.Subscription.SubcriptionType Subscription) {
            Aci.X.IwsLib.Commerce.v2_1.Subscription.ReActivateSubscriptionRequest inValue = new Aci.X.IwsLib.Commerce.v2_1.Subscription.ReActivateSubscriptionRequest();
            inValue.ClientAuth = ClientAuth;
            inValue.UserContext = UserContext;
            inValue.SubscriptionID = SubscriptionID;
            inValue.ReasonCode = ReasonCode;
            Aci.X.IwsLib.Commerce.v2_1.Subscription.ReActivateSubscriptionResponse retVal = ((Aci.X.IwsLib.Commerce.v2_1.Subscription.SubscriptionServicesPortType)(this)).ReActivateSubscription(inValue);
            CompletionResponse = retVal.CompletionResponse;
            Subscription = retVal.Subscription;
            return retVal.RequestReferenceID;
        }
        
        public System.Threading.Tasks.Task<Aci.X.IwsLib.Commerce.v2_1.Subscription.ReActivateSubscriptionResponse> ReActivateSubscriptionAsync(Aci.X.IwsLib.Commerce.v2_1.Subscription.ReActivateSubscriptionRequest request) {
            return base.Channel.ReActivateSubscriptionAsync(request);
        }
    }
}
