SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[spSiteGet](@SiteKeys ID_TABLE READONLY) AS
	SET NOCOUNT ON;
	SELECT * 
		FROM Site s
		WHERE EXISTS (
			SELECT 1
				FROM @SiteKeys k
				WHERE k.ID=s.ID
		)
GO
